package com.atomforge.fdo.dsl.atoms;

import com.atomforge.fdo.atom.AtomDefinition;
import com.atomforge.fdo.atom.AtomTable;

public enum MatAtom implements DslAtom {
    BOOL_VERTICAL_SCROLL,
    BOOL_DISABLED,
    BOOL_DEFAULT,
    BOOL_RESIZE_VERTICAL,
    BOOL_RESIZE_HORIZONTAL,
    BOOL_MODAL,
    BOOL_INVISIBLE,
    BOOL_HIDDEN,
    ORIENTATION,
    CAPACITY,
    FONT_SIS,
    RELATIVE_TAG,
    OBJECT_ID,
    ART_ID,
    WIDTH,
    HEIGHT,
    TITLE_POS,
    RULER,
    OBJECT_COLOR,
    VERTICAL_SPACING,
    ICONIFY_AS,
    PLUS_GROUP,
    SIZE,
    TITLE,
    TITLE_WIDTH,
    BOOL_LIST_ICONS,
    BOOL_GRAPHIC_VIEW,
    BOOL_PALETTE,
    BOOL_HORIZONTAL_SCROLL,
    BOOL_FORCE_SCROLL,
    BOOL_PROTECTED_INPUT,
    BOOL_FORCE_NO_SCROLL,
    BOOL_NON_CLOSEABLE,
    BOOL_EXPORTABLE,
    BOOL_IMPORTABLE,
    BOOL_WRITEABLE,
    BOOL_FLOATING,
    BOOL_CONTIGUOUS,
    BOOL_MENU,
    BOOL_DEFAULT_SEND,
    BOOL_DOUBLE_SPACE,
    OBJECT_TYPE,
    VERT_SCROLL_CAPACITY,
    HORZ_SCROLL_CAPACITY,
    FONT_ID,
    FONT_SIZE,
    FONT_STYLE,
    VALUE,
    BORDER,
    COMMAND_KEY,
    DIRTY_QUERY,
    MANAGED_BY,
    VALIDATION,
    HORIZONTAL_SPACING,
    STYLE_ID,
    MINIMUM,
    MAXIMUM,
    HORZ_SCROLL_VALUE,
    VERT_SCROLL_VALUE,
    BOOL_INVERT,
    POSITION,
    LOG_OBJECT,
    PARAGRAPH,
    SCROLL_THRESHOLD,
    SHORTCUT_KEY,
    SORT_ORDER,
    UNFOCUSED,
    BOOL_PERMANENT,
    BOOL_IGNORE,
    INCREMENT,
    BOOL_NO_BORDER,
    BOOL_MODIFIED,
    LINK_CONTENT_TO_RID,
    BOOL_PRECISE,
    PRECISE_WIDTH,
    PRECISE_HEIGHT,
    PRECISE_X,
    PRECISE_Y,
    COLOR_FACE,
    COLOR_TEXT,
    COLOR_TOP_EDGE,
    COLOR_BOTTOM_EDGE,
    BOOL_GRADUAL_SHADOW,
    FRAME_STYLE,
    TRIGGER_STYLE,
    COLOR_SELECTED,
    COLOR_TEXT_SHADOW,
    TIMER_EVENT,
    TIMER_DURATION,
    BOOL_BACKGROUND_PIC,
    BOOL_BACKGROUND_FLOOD,
    COLOR_FRAME_HILIGHT,
    COLOR_FRAME_SHADOW,
    ART_FRAME,
    ART_ANIMATION_RATE,
    ART_ANIMATION_SEQ,
    BOOL_REPEAT_ANIMATION,
    BOOL_BACKGROUND_TILE,
    CONTEXT_HELP,
    DROP_DATA_TYPE,
    FIELD_SCRIPT,
    ENCODE_TYPE,
    BOOL_FIRST_SCRIPT,
    BOOL_LIST_ALLOW_ENTRY,
    URL,
    BOOL_EXPAND_TO_FIT,
    SINK,
    BOOL_SANE,
    BOOL_URL_SINK,
    BOOL_DROP_AT_TOP,
    FORM_ICON,
    CONTENT_TAG,
    BOOL_LANGUAGE_POPUP,
    LANGUAGE_SENSITIVE,
    BOOL_PALETTE_ART,
    SET_DFLT_EXTRACT_TYPE,
    ART_HINT_WIDTH,
    ART_HINT_HEIGHT,
    ART_HINT_TITLE,
    ART_HINT_PLACEHOLDER_ID,
    ART_HINT_TITLE_X,
    BOOL_TOOL_GROUP,
    ART_HINT_TITLE_Y,
    ART_HINT_TITLE_FONT_SIZE,
    ART_HINT_TITLE_FONT_ID,
    ART_HINT_TITLE_FONT_STYLE,
    BOOL_SMALL_ICON,
    ART_HINT_SELECT_PLACEHOLDER,
    OBJECT_INDEX,
    BOOL_ENCODE_UNICODE,
    TEXT_ON_PICTURE_POS,
    SECURE_FORM,
    FP_COMPOSE_MAIL,
    FP_SEND_IM,
    FP_SAVE_TO_FP,
    BOOL_PAGE_CONTROL,
    BOOL_SPINNER,
    BOOL_DETACHED,
    BOOL_CUSTOMIZABLE,
    BOOL_DETACHABLE,
    BOOL_DOCK_HORIZONTAL,
    BOOL_DOCK_VERTICAL,
    BOOL_CHILDREN_REMOVABLE,
    BOOL_CHILDREN_MOVABLE,
    BOOL_CHILD_REMOVABLE,
    BOOL_CHILD_MOVABLE,
    BOOL_CHILD_LINE_FEED,
    TITLE_APPEND_SCREEN_NAME,
    URL_LIST,
    TAB_SET_CUR_SEL,
    TAB_GET_CUR_SEL,
    BOOL_SHARED_STYLE,
    BOOL_ACTIVE_OFFLINE,
    BOOL_ACTIVE_ONLINE,
    BOOL_INACTIVE_FOR_GUEST,
    BOOL_DROPDOWN_BUTTON,
    BOOL_POPUP_MENU,
    BOOL_IGNORE_URL_LIST,
    POPUP_RELATIVE_ID,
    POPUP_PFC_PATH,
    BOOL_DRAW_FOCUS,
    URL_NEXT,
    URL_PREV,
    URL_PARENT,
    BOOL_LOGGABLE,
    SECURE_FIELD,
    BOOL_HIDE_URL,
    BOOL_AUTO_CLOSEABLE,
    BOOL_SIGNOFF_MENU,
    BOOL_IGNORE_URL,
    BOOL_SAVABLE_TO_PFC,
    BOOL_STATIC_URL,
    INTL_FONT_SIS,
    NAVARROW_POS,
    NAVARROW_ART,
    NAVARROW_POS_X,
    NAVARROW_POS_Y,
    ART_SEQ,
    SAGE_CONTEXT_HELP,
    AUTO_COMPLETE,
    LEFT_SPACING,
    TOP_SPACING,
    RIGHT_SPACING,
    BOTTOM_SPACING,
    SPACING,
    FACTORY_ID,
    TREECTRL_SET_CLASS,
    TITLE_ACCESS,
    CTRL_ATTRIBUTE,
    TITLE_ACCESS_RIDS,
    TITLE_ACCESS_RID,
    BOOL_ALLOW_TABBING,
    BOOL_DEFAULT_TRIGGER,
    USE_STYLE_GUIDE,
    THUMB_SIZE,
    BOOL_HIDE_TICKS,
    COLOR_THUMB,
    COLOR_CHANNEL,
    BOOL_IS_SLIDER;

    private final AtomDefinition def;

    MatAtom() {
        String atomName = "mat_" + name().toLowerCase();
        this.def = AtomTable.loadDefault().findByName(atomName)
            .orElseThrow(() -> new IllegalStateException(
                "Atom not found in registry: " + atomName + 
                ". This indicates a mismatch between DslEnumGenerator and AtomRegistry."));
    }

    @Override
    public AtomDefinition definition() {
        return def;
    }

    public static MatAtom fromAtomNumber(int atomNumber) {
        for (MatAtom atom : values()) {
            if (atom.atomNumber() == atomNumber) {
                return atom;
            }
        }
        return null;
    }

    public static MatAtom fromName(String name) {
        if (name == null) return null;
        String lower = name.toLowerCase();
        for (MatAtom atom : values()) {
            if (atom.atomName().equals(lower)) {
                return atom;
            }
        }
        return null;
    }
}
